import type { Scan, ScanIssueRow } from '@/types'
import { getGrade } from '@/lib/scoring'

const SEVERITY_ORDER = ['critical', 'high', 'medium', 'low', 'info'] as const

function moduleLabel(module: string): string {
  return { seo: 'SEO', geo: 'GEO', ai: 'AI Visibility', security: 'Security' }[module] ?? module.toUpperCase()
}

function escapeCell(text: string | undefined): string {
  return (text ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ')
}

export function generateMarkdownReport(scan: Scan & { scan_issues: ScanIssueRow[] }): string {
  const result = scan.result
  const issues = scan.scan_issues ?? []
  const grade = getGrade(scan.overall_score ?? 0)
  const hostname = (() => { try { return new URL(scan.url).hostname } catch { return scan.url } })()
  const scannedAt = scan.completed_at ? new Date(scan.completed_at).toUTCString() : new Date(scan.created_at).toUTCString()
  const duration = scan.scan_duration ? `${(scan.scan_duration / 1000).toFixed(1)}s` : 'N/A'

  const lines: string[] = []

  lines.push(`# NexSight Report — ${hostname}`)
  lines.push('')
  lines.push(`**URL:** ${scan.url}  `)
  lines.push(`**Scanned:** ${scannedAt}  `)
  lines.push(`**Duration:** ${duration}  `)
  lines.push(`**Overall Score:** ${scan.overall_score ?? 0}/100 (${grade})`)
  lines.push('')

  lines.push('## Module Scores')
  lines.push('')
  lines.push('| Module | Score | Issues |')
  lines.push('|--------|-------|--------|')

  const modules = [
    { label: 'SEO', score: scan.seo_score, module: 'seo' },
    { label: 'GEO', score: scan.geo_score, module: 'geo' },
    { label: 'AI Visibility', score: scan.ai_score, module: 'ai' },
    { label: 'Security', score: scan.sec_score, module: 'security' },
  ]

  for (const m of modules) {
    const count = issues.filter((i) => i.module === m.module).length
    lines.push(`| ${m.label} | ${m.score ?? 0}/100 | ${count} |`)
  }
  lines.push('')

  if (result?.seo?.checks || result?.geo?.checks || result?.ai?.checks || result?.security?.checks) {
    lines.push('## Check Details')
    lines.push('')

    const allChecks = {
      SEO: result.seo?.checks ?? {},
      GEO: result.geo?.checks ?? {},
      'AI Visibility': result.ai?.checks ?? {},
      Security: result.security?.checks ?? {},
    }

    for (const [modLabel, checks] of Object.entries(allChecks)) {
      const checkEntries = Object.entries(checks)
      if (checkEntries.length === 0) continue
      lines.push(`### ${modLabel}`)
      lines.push('')
      lines.push('| Check | Passed | Score | Details |')
      lines.push('|-------|--------|-------|---------|')
      for (const [code, check] of checkEntries) {
        lines.push(`| ${code.toUpperCase()} | ${check.passed ? '✅' : '❌'} | ${check.score}/100 | ${escapeCell(check.details)} |`)
      }
      lines.push('')
    }
  }

  lines.push('## Issues')
  lines.push('')

  for (const severity of SEVERITY_ORDER) {
    const sevIssues = issues.filter((i) => i.severity === severity)
    if (sevIssues.length === 0) continue

    lines.push(`### ${severity.charAt(0).toUpperCase() + severity.slice(1)} (${sevIssues.length})`)
    lines.push('')
    lines.push('| Module | Code | Title | Recommendation |')
    lines.push('|--------|------|-------|----------------|')

    for (const issue of sevIssues) {
      lines.push(`| ${moduleLabel(issue.module)} | ${issue.code} | ${escapeCell(issue.title)} | ${escapeCell(issue.recommendation)} |`)
    }
    lines.push('')
  }

  if (issues.length === 0) {
    lines.push('No issues found. Great job!')
    lines.push('')
  }

  lines.push('---')
  lines.push(`*Generated by NexSight — ${new Date().toUTCString()}*`)

  return lines.join('\n')
}
